/** 120+ frases objetivo para SEO tradicional y descubrimiento en IAs (GEO). */
export const CHILE_USED_CAR_KEYWORDS = [
  "autos usados",
  "autos usados chile",
  "comprar auto",
  "comprar auto usado",
  "comprar auto usado chile",
  "comprar auto barato",
  "autos usados baratos",
  "autos usados baratos chile",
  "automotora autos usados",
  "automotora usados chile",
  "venta autos usados",
  "venta autos usados chile",
  "vehiculos usados",
  "vehiculos usados chile",
  "vehiculos de ocasion",
  "vehículos de ocasión",
  "comprar vehiculo usado",
  "comprar vehículo usado chile",
  "autos seminuevos",
  "autos seminuevos chile",
  "comprar auto seminuevo",
  "automotora santiago",
  "automotora santiago usados",
  "comprar auto santiago",
  "autos usados santiago",
  "autos usados region metropolitana",
  "catalogo autos usados",
  "catalogo autos usados chile",
  "autos usados con fotos",
  "autos usados visor 3d",
  "comprar auto economico",
  "comprar auto económico chile",
  "auto usado financiamiento",
  "financiamiento auto usado chile",
  "comprar auto al contado",
  "comprar camioneta usada",
  "comprar camioneta usada chile",
  "comprar suv usado",
  "comprar suv usado chile",
  "comprar pickup usada",
  "pickup usada chile",
  "comprar auto 4x4 usado",
  "autos 4x4 usados chile",
  "comprar hatchback usado",
  "comprar sedan usado",
  "comprar auto automatico usado",
  "comprar auto automático chile",
  "comprar auto manual usado",
  "autos usados bajo mercado",
  "autos usados precio bajo",
  "ofertas autos usados",
  "ofertas autos usados chile",
  "remate autos usados",
  "vedisa remates autos",
  "vedisa automotora",
  "vehiculos de ocasion vedisa",
  "automotora vedisa remates",
  "comprar auto vedisa",
  "stock autos usados",
  "inventario autos usados chile",
  "autos usados disponibles",
  "comprar auto hoy chile",
  "automotora confiable chile",
  "mejor automotora autos usados",
  "donde comprar auto usado chile",
  "sitio comprar auto usado",
  "pagina autos usados chile",
  "comprar auto usado online chile",
  "comprar auto usado whatsapp",
  "autos usados whatsapp chile",
  "comprar auto usado rm",
  "autos usados valparaiso",
  "autos usados viña del mar",
  "autos usados concepcion",
  "autos usados concepción",
  "autos usados temuco",
  "autos usados puerto montt",
  "autos usados la serena",
  "autos usados antofagasta",
  "permuta auto usado",
  "tasacion auto usado",
  "tasación vehículo usado chile",
  "vender auto usado chile",
  "compraventa autos usados",
  "compraventa vehiculos usados",
  "automotora compraventa santiago",
  "autos usados empresa",
  "flota autos usados",
  "autos usados livianos",
  "autos usados pesados",
  "camiones usados chile",
  "maquinaria usada chile",
  "vehiculo liviano usado",
  "vehiculo pesado usado",
  "auto usado revisado",
  "autos usados con historial",
  "comprar jeep usado chile",
  "comprar toyota usado chile",
  "comprar chevrolet usado chile",
  "comprar nissan usado chile",
  "comprar hyundai usado chile",
  "comprar kia usado chile",
  "comprar mazda usado chile",
  "comprar ford usado chile",
  "comprar mitsubishi usado chile",
  "comprar peugeot usado chile",
  "comprar volkswagen usado chile",
  "comprar bmw usado chile",
  "comprar mercedes usado chile",
  "comprar audi usado chile",
  "comprar auto familiar usado",
  "comprar auto ciudad usado",
  "comprar auto trabajo usado",
  "comprar furgon usado chile",
  "comprar van usada chile",
  "autos usados americano vespucio",
  "automotora americo vespucio 288",
  "vehiculos ocasion santiago",
  "ocasion autos chile",
  "autos segunda mano chile",
  "comprar auto segunda mano",
  "vehiculos segunda mano santiago",
  "automotora ocasion chile",
  "comprar auto ocasion barato",
  "autos usados entrega inmediata",
  "comprar auto stock disponible",
  "vehiculos seminuevos vedisa",
  "vehiculos seminuevos chile precio",
  "automotora vehiculos seminuevos",
  "comprar auto usado sin sorpresas",
  "autos usados transparencia precio",
  "cotizar auto usado chile",
  "consultar auto usado whatsapp",
  "agendar visita automotora santiago",
  "ver autos usados catalogo online",
  "buscar auto usado por patente chile",
  "buscar auto usado por marca chile",
  "filtrar autos usados chile",
  "comparar autos usados chile",
  "autos usados 2024 chile",
  "autos usados 2023 chile",
  "autos usados 2022 chile",
  "autos usados 2021 chile",
  "autos usados 2020 chile",
  "autos usados bajo 5 millones",
  "autos usados bajo 8 millones",
  "autos usados bajo 10 millones",
  "autos usados bajo 15 millones",
  "auto usado barato santiago",
  "mejor precio auto usado chile",
] as const;

export const PRIMARY_KEYWORDS = CHILE_USED_CAR_KEYWORDS.slice(0, 24);

export function keywordsToMetaString(keywords: readonly string[], limit = 40): string {
  return keywords.slice(0, limit).join(", ");
}
