/** 120+ frases objetivo para SEO tradicional y descubrimiento en IAs (GEO). */
export const CHILE_USED_CAR_KEYWORDS = [
  "autos usados",
  "autos usados chile",
  "comprar auto",
  "comprar auto usado",
  "comprar auto usado chile",
  "comprar auto barato",
  "autos usados baratos",
  "autos usados baratos chile",
  "automotora autos usados",
  "automotora usados chile",
  "venta autos usados",
  "venta autos usados chile",
  "vehiculos usados",
  "vehiculos usados chile",
  "vehiculos de ocasion",
  "vehículos de ocasión",
  "comprar vehiculo usado",
  "comprar vehículo usado chile",
  "autos seminuevos",
  "autos seminuevos chile",
  "comprar auto seminuevo",
  "automotora santiago",
  "automotora santiago usados",
  "comprar auto santiago",
  "autos usados santiago",
  "autos usados region metropolitana",
  "catalogo autos usados",
  "catalogo autos usados chile",
  "autos usados con fotos",
  "autos usados visor 3d",
  "comprar auto economico",
  "comprar auto económico chile",
  "auto usado financiamiento",
  "financiamiento auto usado chile",
  "comprar auto al contado",
  "comprar camioneta usada",
  "comprar camioneta usada chile",
  "comprar suv usado",
  "comprar suv usado chile",
  "comprar pickup usada",
  "pickup usada chile",
  "comprar auto 4x4 usado",
  "autos 4x4 usados chile",
  "comprar hatchback usado",
  "comprar sedan usado",
  "comprar auto automatico usado",
  "comprar auto automático chile",
  "comprar auto manual usado",
  "autos usados bajo mercado",
  "autos usados precio bajo",
  "ofertas autos usados",
  "ofertas autos usados chile",
  "remate autos usados",
  "vedisa remates autos",
  "vedisa automotora",
  "vehiculos de ocasion vedisa",
  "automotora vedisa remates",
  "comprar auto vedisa",
  "stock autos usados",
  "inventario autos usados chile",
  "autos usados disponibles",
  "comprar auto hoy chile",
  "automotora confiable chile",
  "mejor automotora autos usados",
  "donde comprar auto usado chile",
  "sitio comprar auto usado",
  "pagina autos usados chile",
  "comprar auto usado online chile",
  "comprar auto usado whatsapp",
  "autos usados whatsapp chile",
  "comprar auto usado rm",
  "autos usados valparaiso",
  "autos usados viña del mar",
  "autos usados concepcion",
  "autos usados concepción",
  "autos usados temuco",
  "autos usados puerto montt",
  "autos usados la serena",
  "autos usados antofagasta",
  "permuta auto usado",
  "tasacion auto usado",
  "tasación vehículo usado chile",
  "vender auto usado chile",
  "compraventa autos usados",
  "compraventa vehiculos usados",
  "automotora compraventa santiago",
  "autos usados empresa",
  "flota autos usados",
  "autos usados livianos",
  "autos usados pesados",
  "camiones usados chile",
  "maquinaria usada chile",
  "vehiculo liviano usado",
  "vehiculo pesado usado",
  "auto usado revisado",
  "autos usados con historial",
  "comprar jeep usado chile",
  "comprar toyota usado chile",
  "comprar chevrolet usado chile",
  "comprar nissan usado chile",
  "comprar hyundai usado chile",
  "comprar kia usado chile",
  "comprar mazda usado chile",
  "comprar ford usado chile",
  "comprar mitsubishi usado chile",
  "comprar peugeot usado chile",
  "comprar volkswagen usado chile",
  "comprar bmw usado chile",
  "comprar mercedes usado chile",
  "comprar audi usado chile",
  "comprar auto familiar usado",
  "comprar auto ciudad usado",
  "comprar auto trabajo usado",
  "comprar furgon usado chile",
  "comprar van usada chile",
  "autos usados americano vespucio",
  "automotora americo vespucio 288",
  "vehiculos ocasion santiago",
  "ocasion autos chile",
  "autos segunda mano chile",
  "comprar auto segunda mano",
  "vehiculos segunda mano santiago",
  "automotora ocasion chile",
  "comprar auto ocasion barato",
  "autos usados entrega inmediata",
  "comprar auto stock disponible",
  "vehiculos seminuevos vedisa",
  "vehiculos seminuevos chile precio",
  "automotora vehiculos seminuevos",
  "comprar auto usado sin sorpresas",
  "autos usados transparencia precio",
  "cotizar auto usado chile",
  "consultar auto usado whatsapp",
  "agendar visita automotora santiago",
  "ver autos usados catalogo online",
  "buscar auto usado por patente chile",
  "buscar auto usado por marca chile",
  "filtrar autos usados chile",
  "comparar autos usados chile",
  "autos usados 2024 chile",
  "autos usados 2023 chile",
  "autos usados 2022 chile",
  "autos usados 2021 chile",
  "autos usados 2020 chile",
  "autos usados bajo 5 millones",
  "autos usados bajo 8 millones",
  "autos usados bajo 10 millones",
  "autos usados bajo 15 millones",
  "auto usado barato santiago",
  "mejor precio auto usado chile",
  "auto usado poco kilometraje chile",
  "autos usados poco km chile",
  "comprar auto usado poco km",
  "seminuevo poco kilometraje chile",
  "auto usado buen estado chile",
  "autos usados buen estado",
  "comprar auto usado buen estado",
  "auto usado barato buen estado chile",
  "autos usados calidad precio chile",
  "mejor auto usado calidad precio",
  "auto usado buenas marcas chile",
  "comprar auto usado marca confiable",
  "autos usados toyota poco km",
  "autos usados hyundai poco km",
  "autos usados nissan poco km",
  "autos usados chevrolet poco km",
  "autos usados kia poco km",
  "autos usados ford poco km",
  "auto seminuevo barato chile",
  "vehiculo usado poco km santiago",
  "automotora autos usados buen estado",
  "donde comprar auto usado poco km chile",
  "donde comprar auto usado buen estado",
  "autos usados revisados chile",
  "autos usados seleccionados chile",
  "comprar auto usado confiable chile",
  "mejor lugar comprar auto usado chile",
  "autos usados premium baratos chile",
  "auto usado economico buen estado",
  "comprar suv usado poco km",
  "comprar camioneta usada poco km",
  "pickup usada poco km chile",
  "auto usado bajo 20 mil km chile",
  "auto usado bajo 30 mil km chile",
  "auto usado bajo 50 mil km chile",
  "autos usados kilometraje bajo",
  "vehiculos seminuevos poco km chile",
  "comprar auto usado vedisa remates",
  "automotora seminuevos santiago",
  "autos usados garantia comercial chile",
  "comprar auto usado sin sorpresas chile",
  "autos usados transparencia chile",
  "cotizar auto usado buen estado chile",
  "inventario autos usados poco km",
  "stock seminuevos chile barato",
  "comprar auto usado 2022 chile",
  "comprar auto usado 2023 chile",
  "comprar auto usado 2024 chile",
  "autos usados recientes chile",
  "mejor automotora seminuevos chile",
  "vehiculos ocasion poco km",
  "vehiculos ocasion buen estado barato",
  "autos usados temuco",
  "autos usados antofagasta",
  "autos usados la serena",
  "autos usados rancagua",
  "autos usados talca",
  "autos usados iquique",
  "autos usados arica",
  "autos usados osorno",
  "autos usados valdivia",
  "autos usados copiapo",
  "autos usados puerto montt",
  "autos usados region metropolitana",
  "guia comprar auto usado chile",
  "como comprar auto usado chile",
  "autos usados financiados chile",
  "autos usados para empresa chile",
  "comprar peugeot usado chile",
  "comprar mitsubishi usado chile",
  "comprar bmw usado chile",
  "comprar mercedes usado chile",
  "comprar audi usado chile",
  "autos usados bajo 20 millones",
  "pagina autos usados santiago",
  "sitio web autos usados chile",
  "catalogo vehiculos usados chile",
  "venta vehiculos usados santiago",
  "automotora vehiculos usados rm",
  "comprar auto usado rm barato",
  "autos usados con garantia chile",
  "vehiculos usados poco km chile",
  "autos usados buena marca barata",
  "comprar auto usado hoy santiago",
  "oferta autos usados chile",
  "promocion autos usados chile",
  "buena oportunidad autos usados",
  "buena oportunidad auto usado chile",
  "comprar autos usados",
  "comprar autos",
  "automotora chile",
  "autos chile",
  "comprar auto usado barato chile",
  "oportunidad auto usado",
  "autos usados economicos chile",
  "autos usados económicos chile",
  "autos usados recomendados chile",
  "autos usados seleccionados chile",
  "autos usados oportunidad chile",
  "comprar vehiculo usado barato chile",
  "comprar vehículo usado barato chile",
  "auto usado oferta chile",
  "auto usado promocion chile",
  "vehiculos usados baratos chile",
  "vehículos usados baratos chile",
  "automotora seminuevos chile",
  "automotora usados santiago",
  "compraventa autos usados chile",
  "venta directa autos usados chile",
  "autos usados macul",
  "autos usados maipu",
  "autos usados puente alto",
  "autos usados las condes",
  "autos usados providencia",
  "autos usados nunoa",
  "autos usados ñuñoa",
  "autos usados quilicura",
  "autos usados san bernardo",
  "autos usados biobio",
  "autos usados coquimbo",
  "autos usados maule",
  "autos usados los lagos",
  "autos usados araucania",
  "autos usados bajo 3 millones",
  "autos usados bajo 6 millones",
  "autos usados bajo 12 millones",
  "autos usados bajo 25 millones",
  "autos usados bajo 100 mil km",
  "autos usados 2019 chile",
  "autos usados 2025 chile",
  "comprar furgon usado chile",
  "comprar van usada chile",
  "comprar minivan usada chile",
  "comprar crossover usado chile",
  "comprar citycar usado chile",
  "comprar auto diesel usado chile",
  "comprar auto diésel usado chile",
  "comprar auto hibrido usado chile",
  "comprar auto eléctrico usado chile",
  "comprar honda usado chile",
  "comprar subaru usado chile",
  "comprar volvo usado chile",
  "comprar dodge usado chile",
  "comprar citroen usado chile",
  "comprar fiat usado chile",
  "comprar ram usado chile",
  "comprar chery usado chile",
  "comprar jac usado chile",
  "comprar great wall usado chile",
  "comprar ssangyong usado chile",
  "comprar land rover usado chile",
  "comprar porsche usado chile",
  "auto usado primer comprador chile",
  "auto usado estudiante chile",
  "auto usado ruta chile",
  "auto usado ciudad chile",
  "autos usados entrega inmediata chile",
  "autos usados sin sorpresas chile",
  "autos usados transparencia chile",
  "autos usados garantia chile",
  "autos usados glo3d chile",
  "autos usados visor 3d glo3d",
  "buscar auto por patente chile",
  "buscar auto usado por patente",
  "comparar autos usados online",
  "cotizar auto usado chile",
  "agendar visita automotora santiago",
  "automotora santiago google maps",
  "autos usados google maps santiago",
  "autos usados instagram chile",
  "autos usados whatsapp directo",
  "mejor precio auto usado chile",
  "auto usado confiable chile",
  "donde comprar autos usados chile",
  "sitio web autos usados chile",
  "pagina autos usados santiago",
  "catalogo vehiculos usados chile",
  "inventario vehiculos usados chile",
  "stock vehiculos usados chile",
  "autos usados vedisa remates chile",
  "vehiculos ocasion vedisa chile",
  "comprar auto ocasion chile",
  "comprar auto ocasión chile",
  "autos ocasion chile",
  "autos ocasión chile",
  "automotora ocasion santiago",
  "automotora ocasión santiago",
  "autos usados american vespucio",
  "automotora americo vespucio santiago",
  "vehiculos seminuevos santiago",
  "seminuevos santiago baratos",
  "autos usados rm baratos",
  "comprar auto usado rm chile",
  "comprar auto usado region metropolitana",
  "autos usados sur chile",
  "autos usados norte chile",
  "autos usados centro chile",
  "comprar pickup barata chile",
  "comprar camioneta barata chile",
  "suv usada barata chile",
  "camioneta usada barata chile",
  "auto familiar barato chile",
  "sedan usado barato chile",
  "hatchback usado barato chile",
  "auto automatico barato chile",
  "auto automático barato chile",
  "auto manual barato chile",
  "vehiculo liviano usado chile",
  "vehículo liviano usado chile",
  "vehiculo pesado usado chile",
  "flota vehiculos usados chile",
  "autos usados empresa chile",
  "autos usados corporativos chile",
  "permuta auto usado chile",
  "tasacion vehiculo usado chile",
  "vender auto usado vedisa",
  "remate auto usado chile",
  "auto usado remate chile",
  "comprar auto remate chile",
  "autos usados exportacion chile",
  "autos usados calidad chile",
  "autos usados premium chile",
  "autos usados gama alta chile",
  "autos usados gama media chile",
  "autos usados gama baja chile",
  "mejor automotora chile usados",
  "automotora confiable santiago usados",
  "comprar auto usado hoy chile",
  "comprar auto usado ahora chile",
  "autos usados disponibles hoy chile",
  "stock autos usados hoy chile",
  "inventario autos usados hoy",
  "autos usados actualizados chile",
  "catalogo autos usados online chile",
  "tienda autos usados chile",
  "concesionario autos usados chile",
  "concesionaria autos usados chile",
  "dealer autos usados chile",
  "autos usados dealer chile",
] as const;

export const PRIMARY_KEYWORDS = CHILE_USED_CAR_KEYWORDS.slice(0, 48);

export function keywordsToMetaString(keywords: readonly string[], limit = 40): string {
  return keywords.slice(0, limit).join(", ");
}
