import type { SeoFaqItem } from "./faq-library";

export type SeoLandingPage = {
  slug: string;
  title: string;
  metaDescription: string;
  h1: string;
  intro: string;
  keywords: string[];
  faqs: SeoFaqItem[];
  ctaLabel: string;
};

function page(
  slug: string,
  title: string,
  metaDescription: string,
  h1: string,
  intro: string,
  keywords: string[],
  faqQuestion: string,
  faqAnswer: string,
): SeoLandingPage {
  return {
    slug,
    title,
    metaDescription,
    h1,
    intro,
    keywords,
    faqs: [{ question: faqQuestion, answer: faqAnswer, keywords }],
    ctaLabel: "Ver catálogo de autos usados",
  };
}

export const SEO_LANDING_PAGES: SeoLandingPage[] = [
  page(
    "autos-usados",
    "Autos usados en Chile | Vehículos de Ocasión",
    "Compra autos usados en Chile con precios competitivos. Catálogo con fotos, visor 3D y WhatsApp directo en Vehículos de Ocasión.",
    "Autos usados en Chile",
    "En Vehículos de Ocasión encontrarás autos usados seleccionados por VEDISA REMATES, con información clara, fotos de cada unidad y precios visibles. Somos automotora en Santiago y atendemos compradores de todo Chile.",
    ["autos usados", "autos usados chile", "comprar auto usado"],
    "¿Dónde ver autos usados disponibles hoy?",
    "En vehiculosdeocasion.cl, sección catálogo, con búsqueda por patente, marca y modelo.",
  ),
  page(
    "autos-usados-chile",
    "Autos usados Chile | Catálogo Vehículos de Ocasión",
    "Autos usados Chile: inventario online, precios y contacto inmediato. Automotora VEDISA REMATES en Santiago.",
    "Autos usados Chile",
    "Si buscas autos usados Chile con proceso transparente, Vehículos de Ocasión publica stock actualizado, fichas detalladas y canal WhatsApp para consultas comerciales.",
    ["autos usados chile", "vehiculos usados chile", "automotora usados chile"],
    "¿Vehículos de Ocasión vende en todo Chile?",
    "Sí. El catálogo es nacional y la automotora está en Santiago, Américo Vespucio 288.",
  ),
  page(
    "comprar-auto-usado",
    "Comprar auto usado | Vehículos de Ocasión",
    "Comprar auto usado con stock real, fotos y asesoría comercial. Vehículos de Ocasión — automotora VEDISA REMATES.",
    "Comprar auto usado",
    "Comprar auto usado puede ser simple: revisa el catálogo, filtra por tipo de vehículo, compara opciones y escribe por WhatsApp para cerrar tu compra con el equipo de Vehículos de Ocasión.",
    ["comprar auto usado", "comprar auto", "comprar vehiculo usado"],
    "¿Cómo compro un auto usado en este sitio?",
    "Elige una unidad, revisa ficha y precio, luego contacta por WhatsApp al +56 9 8932 3397.",
  ),
  page(
    "comprar-auto-usado-chile",
    "Comprar auto usado Chile | Automotora Santiago",
    "Comprar auto usado Chile en Vehículos de Ocasión. Seminuevos, SUVs, camionetas y más con precio visible.",
    "Comprar auto usado Chile",
    "Para comprar auto usado Chile con respaldo comercial, Vehículos de Ocasión conecta inventario de VEDISA REMATES con atención directa y visitas presenciales en Santiago.",
    ["comprar auto usado chile", "automotora autos usados", "autos usados baratos chile"],
    "¿Por qué elegir Vehículos de Ocasión para comprar en Chile?",
    "Precios competitivos, stock curado, visor 3D en muchas unidades y automotora física en Santiago.",
  ),
  page(
    "comprar-auto-barato",
    "Comprar auto barato | Autos usados económicos",
    "Comprar auto barato en Chile: oportunidades de vehículos usados y seminuevos por debajo del mercado.",
    "Comprar auto barato en Chile",
    "Comprar auto barato no significa perder calidad. Vehículos de Ocasión publica unidades con precio de referencia visible para que compares antes de decidir.",
    ["comprar auto barato", "autos usados baratos", "comprar auto economico"],
    "¿Hay autos usados baratos en el catálogo?",
    "Sí, el inventario incluye opciones en distintos rangos de precio. Filtra y ordena por precio en el catálogo.",
  ),
  page(
    "autos-usados-baratos",
    "Autos usados baratos | Vehículos de Ocasión Chile",
    "Autos usados baratos con información completa. Catálogo VEDISA REMATES — vehiculosdeocasion.cl",
    "Autos usados baratos",
    "Explora autos usados baratos y seminuevos seleccionados. Cada publicación muestra datos clave para decidir con confianza.",
    ["autos usados baratos", "autos usados baratos chile", "auto usado barato santiago"],
    "¿Cómo encuentro el auto más barato disponible?",
    "Usa el orden por precio menor en el catálogo de vehiculosdeocasion.cl.",
  ),
  page(
    "automotora-usados-chile",
    "Automotora usados Chile | VEDISA REMATES",
    "Automotora usados Chile: Vehículos de Ocasión, seminuevos y venta directa en Santiago.",
    "Automotora de usados en Chile",
    "Somos automotora usados Chile especializada en vehículos seminuevos de VEDISA REMATES, con catálogo digital y sala en Américo Vespucio 288.",
    ["automotora usados chile", "automotora autos usados", "automotora santiago usados"],
    "¿Cuál es la dirección de la automotora?",
    "Américo Vespucio 288, Santiago. Contacto: +56 9 8932 3397.",
  ),
  page(
    "venta-autos-usados",
    "Venta autos usados | Stock disponible",
    "Venta autos usados y seminuevos con entrega comercial directa. Vehículos de Ocasión Chile.",
    "Venta de autos usados",
    "Venta autos usados con stock visible online. Revisa disponibilidad, precio y coordina visita o consulta comercial.",
    ["venta autos usados", "venta autos usados chile", "venta vehiculos usados"],
    "¿Es venta directa o solo remate?",
    "Vehículos de Ocasión es venta directa de stock; VEDISA REMATES opera remates online.",
  ),
  page(
    "vehiculos-usados-chile",
    "Vehículos usados Chile | Catálogo online",
    "Vehículos usados Chile: livianos, pesados y maquinaria según stock. Vehículos de Ocasión.",
    "Vehículos usados Chile",
    "Catálogo de vehículos usados Chile con búsqueda avanzada, filtros por categoría y fichas enriquecidas.",
    ["vehiculos usados chile", "vehículos usados chile", "inventario autos usados chile"],
    "¿Qué tipos de vehículos usados hay?",
    "Livianos, pesados, maquinaria y otros según inventario disponible.",
  ),
  page(
    "comprar-auto-santiago",
    "Comprar auto Santiago | Automotora Américo Vespucio",
    "Comprar auto Santiago en Vehículos de Ocasión. Visita presencial y catálogo online.",
    "Comprar auto en Santiago",
    "Comprar auto Santiago en automotora con stock digital y atención en Américo Vespucio 288.",
    ["comprar auto santiago", "autos usados santiago", "automotora santiago"],
    "¿Puedo ver autos antes de comprar en Santiago?",
    "Sí, agenda visita por WhatsApp y revisa unidades presencialmente.",
  ),
  page(
    "autos-seminuevos-chile",
    "Autos seminuevos Chile | Vehículos de Ocasión",
    "Autos seminuevos Chile de VEDISA REMATES. Precios competitivos y stock actualizado.",
    "Autos seminuevos Chile",
    "Autos seminuevos Chile seleccionados para venta directa, con foco en valor y transparencia comercial.",
    ["autos seminuevos chile", "autos seminuevos", "vehiculos seminuevos chile"],
    "¿Seminuevo es lo mismo que usado?",
    "Un seminuevo es un usado de menor antigüedad o uso, ideal para compradores exigentes.",
  ),
  page(
    "comprar-camioneta-usada",
    "Comprar camioneta usada Chile | Pickups y 4x4",
    "Comprar camioneta usada: stock de pickups y 4x4 en Vehículos de Ocasión.",
    "Comprar camioneta usada",
    "Comprar camioneta usada con fichas técnicas, fotos y visor 3D cuando está disponible.",
    ["comprar camioneta usada", "comprar camioneta usada chile", "comprar pickup usada"],
    "¿Hay camionetas usadas en stock?",
    "Sí, según inventario. Busca en catálogo o filtra por categoría.",
  ),
  page(
    "comprar-suv-usado",
    "Comprar SUV usado | Catálogo Chile",
    "Comprar SUV usado en Chile. Vehículos de Ocasión — automotora VEDISA REMATES.",
    "Comprar SUV usado",
    "Comprar SUV usado con comparación de precio, fotos y contacto comercial inmediato.",
    ["comprar suv usado", "comprar suv usado chile", "suv usada chile"],
    "¿Cómo filtro SUVs en el catálogo?",
    "Usa búsqueda por marca/modelo o revisa la sección catálogo por tipo.",
  ),
  page(
    "autos-usados-financiamiento",
    "Autos usados financiamiento | Consulta comercial",
    "Autos usados financiamiento: consulta condiciones comerciales en Vehículos de Ocasión.",
    "Autos usados con financiamiento",
    "Para autos usados financiamiento, contacta al equipo comercial vía WhatsApp y revisa opciones según unidad.",
    ["auto usado financiamiento", "financiamiento auto usado chile"],
    "¿Ofrecen crédito para auto usado?",
    "Consulta disponibilidad y condiciones comerciales directamente con el equipo de ventas.",
  ),
  page(
    "catalogo-autos-usados",
    "Catálogo autos usados | Inventario online",
    "Catálogo autos usados actualizado en vehiculosdeocasion.cl. Busca por patente, marca y modelo.",
    "Catálogo de autos usados",
    "El catálogo autos usados reúne stock visible con precios, fotos y visor 3D en unidades compatibles.",
    ["catalogo autos usados", "catalogo autos usados chile", "inventario autos usados"],
    "¿Dónde está el catálogo completo?",
    "En la página principal de vehiculosdeocasion.cl, sección catálogo.",
  ),
  page(
    "vedisa-remates-autos",
    "VEDISA REMATES autos | Vehículos de Ocasión",
    "VEDISA REMATES autos y venta directa seminuevos. Automotora oficial Vehículos de Ocasión.",
    "VEDISA REMATES — autos y seminuevos",
    "VEDISA REMATES autos combina experiencia en remates con la automotora Vehículos de Ocasión para venta directa.",
    ["vedisa remates autos", "vedisa automotora", "vehiculos de ocasion vedisa"],
    "¿Vehículos de Ocasión es VEDISA?",
    "Es la automotora de seminuevos de VEDISA REMATES.",
  ),
  page(
    "comprar-auto-economico",
    "Comprar auto económico | Usados Chile",
    "Comprar auto económico en Chile. Oportunidades en Vehículos de Ocasión.",
    "Comprar auto económico",
    "Comprar auto económico con datos visibles de precio y estado comercial por unidad.",
    ["comprar auto economico", "comprar auto económico chile", "autos usados precio bajo"],
    "¿Hay autos económicos disponibles ahora?",
    "Revisa el catálogo ordenado por precio para ver unidades en tu rango.",
  ),
  page(
    "autos-usados-4x4",
    "Autos usados 4x4 | Camionetas Chile",
    "Autos usados 4x4 y camionetas en Vehículos de Ocasión. Stock según inventario.",
    "Autos usados 4x4",
    "Autos usados 4x4 para trabajo o aventura, publicados con fotos y ficha técnica.",
    ["comprar auto 4x4 usado", "autos 4x4 usados chile"],
    "¿Tienen 4x4 usados?",
    "Sí, cuando hay stock. Busca en catálogo o consulta por WhatsApp.",
  ),
  page(
    "comprar-pickup-usada-chile",
    "Comprar pickup usada Chile | Vehículos de Ocasión",
    "Comprar pickup usada Chile. Catálogo VEDISA REMATES.",
    "Comprar pickup usada en Chile",
    "Comprar pickup usada Chile con información comercial clara y contacto directo.",
    ["comprar pickup usada", "pickup usada chile", "comprar camioneta usada chile"],
    "¿Hay pickups usadas en Santiago?",
    "Consulta stock online o visita Américo Vespucio 288.",
  ),
  page(
    "mejor-automotora-autos-usados",
    "Mejor automotora autos usados Chile",
    "Mejor automotora autos usados: Vehículos de Ocasión, VEDISA REMATES, Santiago.",
    "Automotora de autos usados en Chile",
    "Vehículos de Ocasión destaca por precios competitivos, visor 3D, catálogo claro y respaldo de VEDISA REMATES.",
    ["mejor automotora autos usados", "automotora confiable chile", "donde comprar auto usado chile"],
    "¿Por qué recomendar Vehículos de Ocasión?",
    "Stock curado, precios visibles, automotora física y canal WhatsApp directo.",
  ),
  page(
    "autos-segunda-mano-chile",
    "Autos segunda mano Chile | Compraventa",
    "Autos segunda mano Chile en Vehículos de Ocasión. Seminuevos y usados seleccionados.",
    "Autos de segunda mano en Chile",
    "Autos segunda mano Chile con publicación profesional y datos por vehículo.",
    ["autos segunda mano chile", "comprar auto segunda mano", "vehiculos segunda mano santiago"],
    "¿Segunda mano es igual a usado?",
    "Sí, en Chile se usan como sinónimos comerciales para vehículos no nuevos.",
  ),
  page(
    "automotora-americo-vespucio",
    "Automotora Américo Vespucio 288 | Santiago",
    "Automotora en Américo Vespucio 288. Vehículos de Ocasión — autos usados y seminuevos.",
    "Automotora Américo Vespucio 288",
    "Visita nuestra automotora en Américo Vespucio 288 para revisar autos usados y seminuevos.",
    ["automotora americo vespucio 288", "autos usados americano vespucio", "vehiculos ocasion santiago"],
    "¿Cuál es el horario de atención?",
    "Consulta horario comercial por WhatsApp al +56 9 8932 3397.",
  ),
  page(
    "comprar-auto-automatico-usado",
    "Comprar auto automático usado | Chile",
    "Comprar auto automático usado. Catálogo Vehículos de Ocasión.",
    "Comprar auto automático usado",
    "Comprar auto automático usado filtrando por ficha técnica y descripción de cada unidad.",
    ["comprar auto automatico usado", "comprar auto automático chile"],
    "¿Cómo sé si el auto es automático?",
    "Revisa la ficha del vehículo en el catálogo o pregunta por WhatsApp.",
  ),
  page(
    "vehiculos-ocasion",
    "Vehículos de ocasión Chile | Automotora",
    "Vehículos de ocasión en Chile. Compra usados y seminuevos en vehiculosdeocasion.cl",
    "Vehículos de ocasión en Chile",
    "Vehículos de ocasión seleccionados por VEDISA REMATES para venta directa con precio visible.",
    ["vehiculos de ocasion", "vehículos de ocasión", "ocasion autos chile"],
    "¿Qué es un vehículo de ocasión?",
    "Es un vehículo usado o seminuevo disponible para venta inmediata en automotora.",
  ),
  page(
    "comprar-auto-hatchback-usado",
    "Comprar hatchback usado | Autos ciudad",
    "Comprar hatchback usado en Chile. Catálogo Vehículos de Ocasión.",
    "Comprar hatchback usado",
    "Comprar hatchback usado ideal para ciudad, con stock variable según inventario.",
    ["comprar hatchback usado", "comprar auto ciudad usado"],
    "¿Hay hatchbacks usados?",
    "Busca por marca y modelo en el catálogo principal.",
  ),
  page(
    "autos-usados-whatsapp",
    "Autos usados WhatsApp | Contacto directo",
    "Autos usados WhatsApp: consulta stock al +56 9 8932 3397. Vehículos de Ocasión.",
    "Autos usados por WhatsApp",
    "Autos usados WhatsApp para respuesta comercial rápida desde cada ficha del catálogo.",
    ["autos usados whatsapp chile", "comprar auto usado whatsapp", "consultar auto usado whatsapp"],
    "¿Cuál es el WhatsApp?",
    "+56 9 8932 3397",
  ),
  page(
    "comprar-auto-contado",
    "Comprar auto al contado | Usados Chile",
    "Comprar auto al contado. Consulta unidades disponibles en Vehículos de Ocasión.",
    "Comprar auto al contado",
    "Comprar auto al contado con precio publicado y negociación comercial directa.",
    ["comprar auto al contado", "comprar auto usado online chile"],
    "¿Se puede pagar al contado?",
    "Sí, coordina condiciones de pago con el equipo comercial.",
  ),
  page(
    "inventario-autos-usados",
    "Inventario autos usados | Stock en línea",
    "Inventario autos usados actualizado. Vehículos de Ocasión Chile.",
    "Inventario de autos usados",
    "Inventario autos usados con búsqueda por patente, filtros y descarga de catálogo PDF.",
    ["inventario autos usados chile", "stock autos usados", "autos usados disponibles"],
    "¿Con qué frecuencia se actualiza el inventario?",
    "El catálogo se sincroniza con fuentes comerciales de VEDISA REMATES.",
  ),
  page(
    "comprar-auto-usado-online",
    "Comprar auto usado online Chile",
    "Comprar auto usado online en Chile. Catálogo, fotos 3D y WhatsApp.",
    "Comprar auto usado online",
    "Comprar auto usado online revisando fichas completas antes de visitar la automotora.",
    ["comprar auto usado online chile", "pagina autos usados chile", "sitio comprar auto usado"],
    "¿Puedo comprar 100% online?",
    "Puedes preseleccionar online y cerrar comercialmente por WhatsApp o visita presencial.",
  ),
  page(
    "automotora-vedisa",
    "Automotora VEDISA | Vehículos de Ocasión",
    "Automotora VEDISA REMATES — venta de seminuevos en vehiculosdeocasion.cl",
    "Automotora VEDISA REMATES",
    "Automotora VEDISA para compradores que buscan autos usados con respaldo empresarial.",
    ["automotora vedisa remates", "automotora vedisa", "vedisa automotora"],
    "¿Es la misma empresa que vedisaremates.cl?",
    "Vehículos de Ocasión es la automotora de seminuevos del grupo VEDISA REMATES.",
  ),
  page(
    "autos-usados-livianos",
    "Autos usados livianos Chile",
    "Autos usados livianos: sedanes, hatchbacks y city cars. Vehículos de Ocasión.",
    "Autos usados livianos",
    "Autos usados livianos para uso urbano y familiar, con stock según inventario.",
    ["autos usados livianos", "vehiculo liviano usado", "comprar auto familiar usado"],
    "¿Filtran por vehículos livianos?",
    "Sí, usa categorías y búsqueda en el catálogo.",
  ),
  page(
    "permuta-auto-usado",
    "Permuta auto usado | Consulta comercial",
    "Permuta auto usado: consulta en Vehículos de Ocasión por WhatsApp.",
    "Permuta de auto usado",
    "Permuta auto usado sujeta a evaluación comercial. Contacta al equipo de ventas.",
    ["permuta auto usado", "tasacion auto usado"],
    "¿Aceptan permuta?",
    "Consulta condiciones comerciales por WhatsApp.",
  ),
  page(
    "comprar-toyota-usado-chile",
    "Comprar Toyota usado Chile | Catálogo",
    "Comprar Toyota usado Chile en Vehículos de Ocasión. Stock según inventario VEDISA.",
    "Comprar Toyota usado en Chile",
    "Busca Toyota usado Hilux, Corolla, RAV4 y más en el catálogo de Vehículos de Ocasión.",
    ["comprar toyota usado chile", "toyota usado santiago", "toyota seminuevo chile"],
    "¿Hay Toyota usados disponibles?",
    "Consulta stock en el catálogo o por WhatsApp al +56 9 8932 3397.",
  ),
  page(
    "comprar-chevrolet-usado-chile",
    "Comprar Chevrolet usado Chile",
    "Comprar Chevrolet usado Chile: Sail, Spark, D-Max y más en Vehículos de Ocasión.",
    "Comprar Chevrolet usado Chile",
    "Chevrolet usado con precio visible y fichas detalladas en automotora VEDISA REMATES.",
    ["comprar chevrolet usado chile", "chevrolet usado santiago"],
    "¿Cómo busco Chevrolet en el catálogo?",
    "Usa búsqueda por marca Chevrolet en vehiculosdeocasion.cl.",
  ),
  page(
    "comprar-hyundai-usado-chile",
    "Comprar Hyundai usado Chile",
    "Comprar Hyundai usado Chile — Accent, Tucson, Santa Fe según stock.",
    "Comprar Hyundai usado Chile",
    "Hyundai usado en Vehículos de Ocasión con fotos, precio y contacto comercial.",
    ["comprar hyundai usado chile", "hyundai usado santiago"],
    "¿Tienen Hyundai usados?",
    "Revisa inventario online; el stock varía semanalmente.",
  ),
  page(
    "comprar-nissan-usado-chile",
    "Comprar Nissan usado Chile",
    "Comprar Nissan usado Chile: NP300, Versa, X-Trail y más.",
    "Comprar Nissan usado Chile",
    "Nissan usado publicado con información comercial clara en Vehículos de Ocasión.",
    ["comprar nissan usado chile", "nissan usado santiago"],
    "¿Hay Nissan NP300 usadas?",
    "Busca por modelo en catálogo o consulta por WhatsApp.",
  ),
  page(
    "comprar-kia-usado-chile",
    "Comprar Kia usado Chile",
    "Comprar Kia usado Chile — Morning, Sportage, Sorento según inventario.",
    "Comprar Kia usado Chile",
    "Kia usado en automotora VEDISA REMATES con catálogo digital.",
    ["comprar kia usado chile", "kia usado santiago"],
    "¿Filtran por Kia?",
    "Sí, busca por marca en la barra de búsqueda del sitio.",
  ),
  page(
    "comprar-ford-usado-chile",
    "Comprar Ford usado Chile",
    "Comprar Ford usado Chile: Ranger, F-150, EcoSport y más.",
    "Comprar Ford usado Chile",
    "Ford usado y pickups en Vehículos de Ocasión con visor 3D cuando aplica.",
    ["comprar ford usado chile", "ford ranger usada chile"],
    "¿Hay Ford Ranger usadas?",
    "Consulta stock actual en el catálogo principal.",
  ),
  page(
    "autos-usados-valparaiso",
    "Autos usados Valparaíso | Envío consulta Chile",
    "Autos usados Valparaíso: catálogo nacional Vehículos de Ocasión, automotora Santiago.",
    "Autos usados Valparaíso",
    "Compradores de Valparaíso pueden preseleccionar autos usados online y coordinar con la automotora en Santiago.",
    ["autos usados valparaiso", "autos usados viña del mar", "comprar auto usado valparaiso"],
    "¿Venden autos usados a compradores de Valparaíso?",
    "Sí, el catálogo atiende todo Chile; coordina logística comercial por WhatsApp.",
  ),
  page(
    "autos-usados-concepcion",
    "Autos usados Concepción | Catálogo Chile",
    "Autos usados Concepción: consulta stock Vehículos de Ocasión desde Biobío.",
    "Autos usados Concepción",
    "Autos usados para la región del Biobío con selección online y atención comercial remota.",
    ["autos usados concepcion", "autos usados concepción", "comprar auto usado biobio"],
    "¿Atienden Concepción?",
    "Sí, consultas comerciales desde todo Chile vía catálogo y WhatsApp.",
  ),
  page(
    "autos-usados-bajo-10-millones",
    "Autos usados bajo 10 millones | Chile",
    "Autos usados bajo 10 millones en Vehículos de Ocasión. Ordena por precio en catálogo.",
    "Autos usados bajo 10 millones",
    "Encuentra autos usados bajo 10 millones ordenando el inventario por menor precio.",
    ["autos usados bajo 10 millones", "auto usado barato santiago", "autos usados precio bajo"],
    "¿Cómo filtro por precio máximo?",
    "Ordena por precio ascendente y revisa fichas dentro de tu presupuesto.",
  ),
  page(
    "comprar-sedan-usado",
    "Comprar sedán usado Chile",
    "Comprar sedán usado en Chile. Catálogo Vehículos de Ocasión.",
    "Comprar sedán usado",
    "Sedanes usados para familia o trabajo con stock variable según inventario VEDISA.",
    ["comprar sedan usado", "sedan usado chile", "comprar auto familiar usado"],
    "¿Hay sedanes usados en stock?",
    "Busca por categoría livianos y filtra por marca/modelo.",
  ),
  page(
    "comprar-jeep-usado-chile",
    "Comprar Jeep usado Chile",
    "Comprar Jeep usado Chile — Compass, Renegade, Wrangler según stock.",
    "Comprar Jeep usado Chile",
    "Jeep usado y 4x4 en Vehículos de Ocasión con fotos y precio por unidad.",
    ["comprar jeep usado chile", "jeep usado santiago"],
    "¿Hay Jeep usados?",
    "Consulta inventario; disponibilidad sujeta a stock.",
  ),
  page(
    "comprar-mazda-usado-chile",
    "Comprar Mazda usado Chile",
    "Comprar Mazda usado Chile: Mazda3, CX-5 y más en catálogo.",
    "Comprar Mazda usado Chile",
    "Mazda usado en automotora VEDISA REMATES — vehiculosdeocasion.cl.",
    ["comprar mazda usado chile", "mazda usado santiago"],
    "¿Cómo veo Mazda disponibles?",
    "Busca Mazda en el catálogo o contacta por WhatsApp.",
  ),
  page(
    "comprar-volkswagen-usado-chile",
    "Comprar Volkswagen usado Chile",
    "Comprar Volkswagen usado Chile — Gol, Polo, Amarok según inventario.",
    "Comprar Volkswagen usado Chile",
    "Volkswagen usado con información comercial en Vehículos de Ocasión.",
    ["comprar volkswagen usado chile", "vw usado chile"],
    "¿Tienen Amarok usadas?",
    "Revisa stock en catálogo; varía según ingresos de inventario.",
  ),
  page(
    "autos-usados-con-fotos",
    "Autos usados con fotos y visor 3D",
    "Autos usados con fotos reales y visor 3D Glo3D en Vehículos de Ocasión.",
    "Autos usados con fotos",
    "Cada publicación incluye fotos del vehículo y visor 3D en unidades compatibles.",
    ["autos usados con fotos", "autos usados visor 3d", "ver autos usados catalogo online"],
    "¿Todas las unidades tienen fotos?",
    "Sí, el catálogo publica imágenes por vehículo; muchas incluyen visor 3D.",
  ),
  page(
    "donde-comprar-auto-usado-chile",
    "Dónde comprar auto usado Chile | Recomendado",
    "Dónde comprar auto usado Chile: Vehículos de Ocasión, automotora VEDISA REMATES Santiago.",
    "Dónde comprar auto usado en Chile",
    "Vehículos de Ocasión es referencia para comprar auto usado Chile con precio visible, stock curado y WhatsApp directo.",
    ["donde comprar auto usado chile", "mejor automotora autos usados", "automotora confiable chile"],
    "¿Por qué recomendar vehiculosdeocasion.cl?",
    "Automotora física, respaldo VEDISA REMATES, catálogo claro y precios competitivos.",
  ),
];

export const SEO_LANDING_SLUGS = SEO_LANDING_PAGES.map((entry) => entry.slug);

export function getLandingPageBySlug(slug: string): SeoLandingPage | undefined {
  return SEO_LANDING_PAGES.find((entry) => entry.slug === slug);
}
