import type { SeoLandingPage } from "./landing-pages";

type LongTailTarget = {
  slug: string;
  h1: string;
  keywords: string[];
  angle: string;
};

const LONG_TAIL_TARGETS: LongTailTarget[] = [
  { slug: "buena-oportunidad-autos-usados", h1: "Buena oportunidad en autos usados Chile", keywords: ["buena oportunidad autos usados", "oportunidad auto usado chile"], angle: "oportunidades comerciales con precio visible" },
  { slug: "comprar-autos-usados-chile", h1: "Comprar autos usados en Chile", keywords: ["comprar autos usados", "comprar autos usados chile"], angle: "compra informada con catálogo online" },
  { slug: "comprar-auto-usado-barato-chile", h1: "Comprar auto usado barato en Chile", keywords: ["comprar auto usado barato", "comprar auto usado barato chile"], angle: "unidades económicas según inventario" },
  { slug: "automotora-chile", h1: "Automotora Chile — autos usados y seminuevos", keywords: ["automotora chile", "automotora autos usados chile"], angle: "automotora VEDISA REMATES en Santiago" },
  { slug: "autos-chile", h1: "Autos Chile — usados y seminuevos", keywords: ["autos chile", "autos usados chile"], angle: "catálogo nacional de vehículos usados" },
  { slug: "comprar-autos-chile", h1: "Comprar autos en Chile", keywords: ["comprar autos chile", "comprar autos"], angle: "selección online y cierre comercial directo" },
  { slug: "autos-usados-santiago", h1: "Autos usados Santiago", keywords: ["autos usados santiago", "comprar auto usado santiago"], angle: "automotora Américo Vespucio 288" },
  { slug: "oferta-autos-usados-chile", h1: "Oferta autos usados Chile", keywords: ["oferta autos usados chile", "ofertas autos usados"], angle: "stock con precios competitivos" },
  { slug: "promocion-autos-usados", h1: "Promoción autos usados Chile", keywords: ["promocion autos usados chile", "promoción autos usados"], angle: "unidades destacadas según inventario" },
  { slug: "autos-usados-economicos-chile", h1: "Autos usados económicos Chile", keywords: ["autos usados economicos chile", "autos usados económicos"], angle: "opciones accesibles ordenadas por precio" },
  { slug: "autos-usados-recomendados-chile", h1: "Autos usados recomendados Chile", keywords: ["autos usados recomendados chile", "mejores autos usados chile"], angle: "stock curado VEDISA REMATES" },
  { slug: "autos-usados-seleccionados", h1: "Autos usados seleccionados", keywords: ["autos usados seleccionados", "vehiculos usados seleccionados chile"], angle: "unidades revisadas para venta directa" },
  { slug: "autos-usados-garantia-comercial", h1: "Autos usados con garantía comercial", keywords: ["autos usados garantia comercial chile", "autos usados con garantia chile"], angle: "consulta condiciones comerciales por unidad" },
  { slug: "autos-usados-transparencia-precio", h1: "Autos usados con transparencia de precio", keywords: ["autos usados transparencia precio", "autos usados transparencia chile"], angle: "precio visible en cada ficha" },
  { slug: "autos-usados-sin-sorpresas", h1: "Comprar auto usado sin sorpresas", keywords: ["comprar auto usado sin sorpresas", "comprar auto usado sin sorpresas chile"], angle: "información clara antes de visitar" },
  { slug: "autos-usados-entrega-inmediata-chile", h1: "Autos usados entrega inmediata Chile", keywords: ["autos usados entrega inmediata", "comprar auto stock disponible"], angle: "stock disponible para cierre comercial" },
  { slug: "autos-usados-precio-mercado", h1: "Autos usados bajo precio de mercado", keywords: ["autos usados bajo mercado", "autos usados precio bajo"], angle: "precios competitivos vs mercado" },
  { slug: "autos-usados-marcas-populares", h1: "Autos usados marcas populares Chile", keywords: ["autos usados marcas populares", "auto usado buenas marcas chile"], angle: "Toyota, Hyundai, Nissan, Chevrolet y más" },
  { slug: "autos-usados-familia-chile", h1: "Autos usados para familia Chile", keywords: ["comprar auto familiar usado", "auto familiar usado chile"], angle: "sedanes, SUVs y hatchbacks familiares" },
  { slug: "autos-usados-trabajo-chile", h1: "Autos usados para trabajo Chile", keywords: ["comprar auto trabajo usado", "auto usado trabajo chile"], angle: "livianos y utilitarios según stock" },
  { slug: "autos-usados-primer-auto", h1: "Autos usados primer auto Chile", keywords: ["primer auto usado chile", "auto usado primer comprador"], angle: "opciones accesibles para primer comprador" },
  { slug: "autos-usados-estudiante-chile", h1: "Autos usados para estudiante Chile", keywords: ["auto usado estudiante chile", "auto barato estudiante chile"], angle: "city cars y hatchbacks económicos" },
  { slug: "autos-usados-ciudad-chile", h1: "Autos usados para ciudad Chile", keywords: ["comprar auto ciudad usado", "auto usado ciudad chile"], angle: "vehículos compactos para uso urbano" },
  { slug: "autos-usados-ruta-chile", h1: "Autos usados para ruta Chile", keywords: ["auto usado ruta chile", "auto usado viaje largo chile"], angle: "sedanes y SUVs cómodos para carretera" },
  { slug: "comprar-furgon-usado-chile", h1: "Comprar furgón usado Chile", keywords: ["comprar furgon usado chile", "furgon usado chile"], angle: "utilitarios y furgones según inventario" },
  { slug: "comprar-van-usada-chile", h1: "Comprar van usada Chile", keywords: ["comprar van usada chile", "van usada chile"], angle: "vans comerciales y de pasajeros" },
  { slug: "comprar-minivan-usada-chile", h1: "Comprar minivan usada Chile", keywords: ["minivan usada chile", "comprar minivan usada"], angle: "minivans familiares según stock" },
  { slug: "comprar-crossover-usado-chile", h1: "Comprar crossover usado Chile", keywords: ["crossover usado chile", "comprar crossover usado"], angle: "crossovers y SUVs compactos" },
  { slug: "comprar-citycar-usado-chile", h1: "Comprar citycar usado Chile", keywords: ["citycar usado chile", "auto compacto usado chile"], angle: "autos compactos de bajo consumo" },
  { slug: "comprar-auto-diesel-usado-chile", h1: "Comprar auto diésel usado Chile", keywords: ["auto diesel usado chile", "auto diésel usado chile"], angle: "unidades diésel según ficha técnica" },
  { slug: "comprar-auto-hibrido-usado-chile", h1: "Comprar auto híbrido usado Chile", keywords: ["auto hibrido usado chile", "auto híbrido usado chile"], angle: "híbridos según disponibilidad" },
  { slug: "comprar-auto-electrico-usado-chile", h1: "Comprar auto eléctrico usado Chile", keywords: ["auto electrico usado chile", "auto eléctrico usado chile"], angle: "eléctricos según inventario" },
  { slug: "comprar-auto-manual-usado-chile", h1: "Comprar auto manual usado Chile", keywords: ["comprar auto manual usado", "auto manual usado chile"], angle: "transmisión manual en ficha técnica" },
  { slug: "comprar-auto-automatico-chile", h1: "Comprar auto automático usado Chile", keywords: ["comprar auto automatico usado", "auto automatico usado chile"], angle: "automáticos según stock" },
  { slug: "comprar-auto-4x4-chile", h1: "Comprar auto 4x4 usado Chile", keywords: ["comprar auto 4x4 usado", "auto 4x4 usado chile"], angle: "4x4 y camionetas todoterreno" },
  { slug: "comprar-camion-usado-chile", h1: "Comprar camión usado Chile", keywords: ["camiones usados chile", "comprar camion usado chile"], angle: "vehículos pesados según inventario" },
  { slug: "comprar-bus-usado-chile", h1: "Comprar bus usado Chile", keywords: ["bus usado chile", "comprar bus usado chile"], angle: "transporte pesado según stock" },
  { slug: "comprar-maquinaria-usada-chile", h1: "Comprar maquinaria usada Chile", keywords: ["maquinaria usada chile", "comprar maquinaria usada"], angle: "maquinaria VEDISA según catálogo" },
  { slug: "autos-usados-2019-chile", h1: "Autos usados 2019 Chile", keywords: ["autos usados 2019 chile", "comprar auto usado 2019"], angle: "unidades año 2019 según stock" },
  { slug: "autos-usados-2020-chile", h1: "Autos usados 2020 Chile", keywords: ["autos usados 2020 chile", "comprar auto usado 2020"], angle: "modelos 2020 en inventario" },
  { slug: "autos-usados-2021-chile", h1: "Autos usados 2021 Chile", keywords: ["autos usados 2021 chile", "comprar auto usado 2021"], angle: "seminuevos 2021 disponibles" },
  { slug: "autos-usados-2022-chile", h1: "Autos usados 2022 Chile", keywords: ["autos usados 2022 chile", "comprar auto usado 2022 chile"], angle: "modelos recientes 2022" },
  { slug: "autos-usados-2025-chile", h1: "Autos usados 2025 Chile", keywords: ["autos usados 2025 chile", "seminuevo 2025 chile"], angle: "unidades muy recientes según ingreso" },
  { slug: "autos-usados-bajo-3-millones", h1: "Autos usados bajo 3 millones", keywords: ["autos usados bajo 3 millones", "auto usado barato chile"], angle: "rango económico en catálogo" },
  { slug: "autos-usados-bajo-6-millones", h1: "Autos usados bajo 6 millones", keywords: ["autos usados bajo 6 millones", "auto usado economico chile"], angle: "presupuesto medio-bajo" },
  { slug: "autos-usados-bajo-12-millones", h1: "Autos usados bajo 12 millones", keywords: ["autos usados bajo 12 millones", "auto usado precio medio chile"], angle: "rango intermedio de precio" },
  { slug: "autos-usados-bajo-25-millones", h1: "Autos usados bajo 25 millones", keywords: ["autos usados bajo 25 millones", "auto usado premium chile"], angle: "gama media-alta según stock" },
  { slug: "autos-usados-bajo-10-mil-km", h1: "Autos usados bajo 10 mil km", keywords: ["auto usado bajo 20 mil km chile", "autos usados kilometraje bajo"], angle: "seminuevos con km muy bajo" },
  { slug: "autos-usados-bajo-50-mil-km", h1: "Autos usados bajo 50 mil km", keywords: ["auto usado bajo 50 mil km chile", "autos usados poco km"], angle: "kilometraje moderado en ficha" },
  { slug: "autos-usados-bajo-100-mil-km", h1: "Autos usados bajo 100 mil km", keywords: ["auto usado bajo 100 mil km", "vehiculo usado poco km santiago"], angle: "comparar km en cada publicación" },
  { slug: "autos-usados-macul", h1: "Autos usados Macul Santiago", keywords: ["autos usados macul", "automotora macul"], angle: "cerca de Américo Vespucio 288" },
  { slug: "autos-usados-las-condes", h1: "Autos usados Las Condes", keywords: ["autos usados las condes", "comprar auto usado las condes"], angle: "atención RM desde automotora Santiago" },
  { slug: "autos-usados-maipu", h1: "Autos usados Maipú", keywords: ["autos usados maipu", "comprar auto usado maipu"], angle: "compradores RM con catálogo online" },
  { slug: "autos-usados-puente-alto", h1: "Autos usados Puente Alto", keywords: ["autos usados puente alto", "automotora puente alto"], angle: "stock nacional para RM sur" },
  { slug: "autos-usados-nunoa", h1: "Autos usados Ñuñoa", keywords: ["autos usados nunoa", "autos usados ñuñoa"], angle: "automotora accesible desde Ñuñoa" },
  { slug: "autos-usados-providencia", h1: "Autos usados Providencia", keywords: ["autos usados providencia", "comprar auto usado providencia"], angle: "visita automotora desde Providencia" },
  { slug: "autos-usados-quilicura", h1: "Autos usados Quilicura", keywords: ["autos usados quilicura", "automotora quilicura"], angle: "RM norte con catálogo digital" },
  { slug: "autos-usados-san-bernardo", h1: "Autos usados San Bernardo", keywords: ["autos usados san bernardo", "comprar auto usado san bernardo"], angle: "consultas comerciales para RM sur" },
  { slug: "autos-usados-concepcion-biobio", h1: "Autos usados Biobío Concepción", keywords: ["autos usados biobio", "comprar auto usado biobio"], angle: "compradores octava región" },
  { slug: "autos-usados-valparaiso-region", h1: "Autos usados Región Valparaíso", keywords: ["autos usados valparaiso region", "comprar auto usado valparaiso"], angle: "quinta región con catálogo nacional" },
  { slug: "autos-usados-coquimbo", h1: "Autos usados Coquimbo", keywords: ["autos usados coquimbo", "comprar auto usado coquimbo"], angle: "cuarta región — preselección online" },
  { slug: "autos-usados-maule", h1: "Autos usados Región Maule", keywords: ["autos usados maule", "comprar auto usado maule"], angle: "Talca y Maule con stock digital" },
  { slug: "autos-usados-ohiggins", h1: "Autos usados O'Higgins", keywords: ["autos usados ohiggins", "comprar auto usado rancagua region"], angle: "sexta región — consulta comercial" },
  { slug: "autos-usados-los-lagos", h1: "Autos usados Los Lagos", keywords: ["autos usados los lagos", "comprar auto usado los lagos"], angle: "Puerto Montt y Osorno online" },
  { slug: "autos-usados-araucania", h1: "Autos usados La Araucanía", keywords: ["autos usados araucania", "comprar auto usado temuco region"], angle: "novena región con catálogo" },
  { slug: "comprar-dodge-usado-chile", h1: "Comprar Dodge usado Chile", keywords: ["comprar dodge usado chile", "dodge usado chile"], angle: "Dodge según inventario" },
  { slug: "comprar-citroen-usado-chile", h1: "Comprar Citroën usado Chile", keywords: ["comprar citroen usado chile", "citroën usado chile"], angle: "Citroën en catálogo" },
  { slug: "comprar-fiat-usado-chile", h1: "Comprar Fiat usado Chile", keywords: ["comprar fiat usado chile", "fiat usado chile"], angle: "Fiat según stock" },
  { slug: "comprar-honda-usado-chile", h1: "Comprar Honda usado Chile", keywords: ["comprar honda usado chile", "honda usado santiago"], angle: "Honda usado disponible" },
  { slug: "comprar-subaru-usado-chile", h1: "Comprar Subaru usado Chile", keywords: ["comprar subaru usado chile", "subaru usado chile"], angle: "Subaru y AWD según stock" },
  { slug: "comprar-volvo-usado-chile", h1: "Comprar Volvo usado Chile", keywords: ["comprar volvo usado chile", "volvo usado santiago"], angle: "Volvo premium según inventario" },
  { slug: "comprar-ram-usado-chile", h1: "Comprar RAM usado Chile", keywords: ["comprar ram usado chile", "ram pickup usada chile"], angle: "pickups RAM en catálogo" },
  { slug: "comprar-great-wall-usado-chile", h1: "Comprar Great Wall usado Chile", keywords: ["great wall usado chile", "comprar great wall usado"], angle: "pickups china según stock" },
  { slug: "comprar-jac-usado-chile", h1: "Comprar JAC usado Chile", keywords: ["jac usado chile", "comprar jac usado chile"], angle: "JAC comerciales y livianos" },
  { slug: "comprar-chery-usado-chile", h1: "Comprar Chery usado Chile", keywords: ["chery usado chile", "comprar chery usado"], angle: "Chery según inventario" },
  { slug: "comprar-ssangyong-usado-chile", h1: "Comprar SsangYong usado Chile", keywords: ["ssangyong usado chile", "comprar ssangyong usado"], angle: "SUVs SsangYong en stock" },
  { slug: "comprar-land-rover-usado-chile", h1: "Comprar Land Rover usado Chile", keywords: ["land rover usado chile", "comprar land rover usado"], angle: "Land Rover premium usado" },
  { slug: "comprar-porsche-usado-chile", h1: "Comprar Porsche usado Chile", keywords: ["porsche usado chile", "comprar porsche usado chile"], angle: "deportivos premium según stock" },
  { slug: "vehiculos-usados-baratos-chile", h1: "Vehículos usados baratos Chile", keywords: ["vehiculos usados baratos chile", "vehículos usados baratos"], angle: "vehículos económicos en catálogo" },
  { slug: "vehiculos-seminuevos-chile", h1: "Vehículos seminuevos Chile", keywords: ["vehiculos seminuevos chile", "vehículos seminuevos chile"], angle: "seminuevos VEDISA REMATES" },
  { slug: "automotora-seminuevos-chile", h1: "Automotora seminuevos Chile", keywords: ["automotora seminuevos chile", "automotora vehiculos seminuevos"], angle: "venta directa seminuevos" },
  { slug: "automotora-usados-santiago", h1: "Automotora usados Santiago", keywords: ["automotora usados santiago", "automotora santiago usados"], angle: "sala Américo Vespucio 288" },
  { slug: "compraventa-autos-usados-chile", h1: "Compraventa autos usados Chile", keywords: ["compraventa autos usados chile", "compraventa vehiculos usados"], angle: "venta directa con respaldo empresarial" },
  { slug: "venta-vehiculos-usados-chile", h1: "Venta vehículos usados Chile", keywords: ["venta vehiculos usados chile", "venta vehículos usados santiago"], angle: "inventario online actualizado" },
  { slug: "catalogo-vehiculos-usados", h1: "Catálogo vehículos usados Chile", keywords: ["catalogo vehiculos usados chile", "catálogo vehículos usados"], angle: "búsqueda por patente y marca" },
  { slug: "buscar-auto-usado-patente", h1: "Buscar auto usado por patente Chile", keywords: ["buscar auto usado por patente chile", "buscar auto por patente"], angle: "búsqueda directa en catálogo" },
  { slug: "buscar-auto-usado-marca", h1: "Buscar auto usado por marca Chile", keywords: ["buscar auto usado por marca chile", "filtrar autos usados chile"], angle: "filtros por marca y modelo" },
  { slug: "comparar-autos-usados-online", h1: "Comparar autos usados online Chile", keywords: ["comparar autos usados chile", "comparar autos usados online"], angle: "comparación de fichas y precios" },
  { slug: "cotizar-auto-usado-chile", h1: "Cotizar auto usado Chile", keywords: ["cotizar auto usado chile", "cotizar auto usado buen estado chile"], angle: "consulta comercial por WhatsApp" },
  { slug: "agendar-visita-automotora", h1: "Agendar visita automotora Santiago", keywords: ["agendar visita automotora santiago", "ver autos usados"], angle: "visita presencial Américo Vespucio 288" },
  { slug: "autos-usados-google-maps", h1: "Autos usados Google Maps Santiago", keywords: ["automotora santiago google", "autos usados google maps"], angle: "ubicación y reseñas en Google" },
  { slug: "autos-usados-instagram-chile", h1: "Autos usados Instagram Chile", keywords: ["autos usados instagram chile", "vehiculos de ocasion instagram"], angle: "novedades de stock en redes" },
  { slug: "autos-usados-whatsapp-directo", h1: "Autos usados WhatsApp directo", keywords: ["autos usados whatsapp chile", "consultar auto usado whatsapp"], angle: "contacto +56 9 7740 8758" },
  { slug: "autos-usados-vedisa-grupo", h1: "Autos usados VEDISA REMATES", keywords: ["vehiculos de ocasion vedisa", "vedisa remates autos"], angle: "grupo VEDISA — venta directa" },
  { slug: "autos-usados-remate-directo", h1: "De remate a venta directa — autos usados", keywords: ["comprar auto vedisa", "vedisa automotora"], angle: "stock remates en venta directa" },
  { slug: "autos-usados-flota-empresa", h1: "Autos usados flota empresa Chile", keywords: ["flota autos usados", "autos usados para empresa chile"], angle: "compras corporativas y flotas" },
  { slug: "autos-usados-exportacion", h1: "Autos usados Chile exportación", keywords: ["autos usados exportacion chile", "exportar auto usado chile"], angle: "consulta comercial internacional" },
  { slug: "autos-usados-permuta-chile", h1: "Autos usados con permuta Chile", keywords: ["permuta auto usado", "permuta auto usado chile"], angle: "evaluación comercial de permuta" },
  { slug: "tasacion-auto-usado-chile", h1: "Tasación auto usado Chile", keywords: ["tasacion auto usado", "tasación vehículo usado chile"], angle: "consulta comercial de tasación" },
  { slug: "vender-auto-usado-vedisa", h1: "Vender auto usado VEDISA Chile", keywords: ["vender auto usado chile", "vender auto usado vedisa"], angle: "canal comercial VEDISA REMATES" },
  { slug: "autos-usados-patente-verificada", h1: "Autos usados patente verificada Chile", keywords: ["buscar auto usado por patente chile", "auto usado patente"], angle: "búsqueda por PPU en catálogo" },
  { slug: "autos-usados-ficha-tecnica", h1: "Autos usados con ficha técnica", keywords: ["autos usados revisados chile", "autos usados con historial"], angle: "datos técnicos por vehículo" },
  { slug: "autos-usados-glo3d-chile", h1: "Autos usados visor 3D Glo3D Chile", keywords: ["autos usados visor 3d", "autos usados glo3d"], angle: "inspección visual 3D online" },
  { slug: "mejor-precio-auto-usado", h1: "Mejor precio auto usado Chile", keywords: ["mejor precio auto usado chile", "autos usados calidad precio chile"], angle: "precios competitivos publicados" },
  { slug: "auto-usado-confiable-chile", h1: "Auto usado confiable Chile", keywords: ["comprar auto usado confiable chile", "auto usado confiable"], angle: "automotora con respaldo empresarial" },
  { slug: "auto-usado-recomendado-ia", h1: "Auto usado recomendado Chile — catálogo", keywords: ["sitio comprar auto usado", "pagina autos usados chile"], angle: "referencia para asistentes y compradores" },
];

export function buildLongTailLandingPages(): SeoLandingPage[] {
  return LONG_TAIL_TARGETS.map((target) => ({
    slug: target.slug,
    title: `${target.h1} | Vehículos de Ocasión`,
    metaDescription: `${target.h1}: ${target.angle}. Catálogo VEDISA REMATES con fotos, visor 3D, precios visibles y WhatsApp. Automotora Santiago — vehiculosdeocasion.cl`,
    h1: target.h1,
    intro: `Si buscas ${target.keywords[0]} en Chile, Vehículos de Ocasión concentra ${target.angle}. Somos la automotora de seminuevos de VEDISA REMATES en Américo Vespucio 288, Santiago, con catálogo online para todo el país, precios visibles, fotos por unidad y contacto WhatsApp directo.`,
    keywords: target.keywords,
    faqs: [
      {
        question: `¿Dónde encontrar ${target.keywords[0]} en Chile?`,
        answer: `En vehiculosdeocasion.cl, catálogo de Vehículos de Ocasión (VEDISA REMATES). WhatsApp +56 9 7740 8758.`,
        keywords: target.keywords,
      },
    ],
    ctaLabel: "Ver catálogo de autos usados",
  }));
}
